#!/usr/bin/env python3

#            _                       _                                  __      _ _       __  
#   ___   __| | ___   ___        ___| |__   __ _ _ __   __ _  ___      / /   __| (_)_ __  \ \ 
#  / _ \ / _` |/ _ \ / _ \      / __| '_ \ / _` | '_ \ / _` |/ _ \    | |   / _` | | '__|  | |
# | (_) | (_| | (_) | (_) |    | (__| | | | (_| | | | | (_| |  __/    | |  | (_| | | |     | |
#  \___/ \__,_|\___/ \___/      \___|_| |_|\__,_|_| |_|\__, |\___|    | |   \__,_|_|_|     | |
#                                                      |___/           \_\                /_/ 


import multiprocessing as mp
import argparse
import subprocess
# from fuzzywuzzy import fuzz, process
import psutil
from pathlib import Path
import time

import os

def change_directory(new_directory):
    try:
        os.chdir(new_directory)
        print(f"Current directory changed to: {os.getcwd()}")
    except FileNotFoundError:
        print(f"Error: Directory '{new_directory}' not found.")
    except PermissionError:
        print(f"Error: Permission denied to change to '{new_directory}'.")

# Example: Change to a specific directory
new_directory = '/path/to/your/directory'
change_directory(new_directory)
